version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - pip_cache:/root/.cache/pip
    environment:
      - FLASK_ENV=production

volumes:
  pip_cache: 