version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./model:/app/model
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1  # Для корректного вывода логов

volumes:
  pip_cache: 